services:
  backend:
    build:
      context: ..
      dockerfile: docker/server.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../server:/app

  frontend:
    build:
      context: ..
      dockerfile: docker/client.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../client:/app
      - frontend_node_modules:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  frontend_node_modules:
